version: "3.9" 

services:
  python-app:
    build: .
    container_name: python_app_container
    volumes:
      - .:/app
    working_dir: /app
    command: python run.py
    ports:
      - "8000:8000"
