version: "3.9" 

services:
  python-app:
    build: .
    container_name: python_app_container
    volumes:
      - .:/app
    networks:
      - my_bridge_network
    working_dir: /app
    command: uwsgi --ini uwsgi.ini
    ports:
      - "5000:5000"

networks:
  my_bridge_network:
    external: true
    

